// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB4LkJ8rp_pbGFQ42mozL0KA9ZzXvzHRU',
    appId: '1:931846761617:web:5d1542c326a9981e7da330',
    messagingSenderId: '931846761617',
    projectId: 'j3d-sq',
    authDomain: 'j3d-sq.firebaseapp.com',
    storageBucket: 'j3d-sq.firebasestorage.app',
    measurementId: 'G-FXD1PCWYQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuRV-qR8Bctb2Py7JRB0S_aYNVDZ6UrMM',
    appId: '1:931846761617:android:6685bf52cf524ad17da330',
    messagingSenderId: '931846761617',
    projectId: 'j3d-sq',
    storageBucket: 'j3d-sq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCY_hYpzS68qIXdq1I-c8qSCnu1yrOWCk',
    appId: '1:931846761617:ios:8285bb0d8c9bd6527da330',
    messagingSenderId: '931846761617',
    projectId: 'j3d-sq',
    storageBucket: 'j3d-sq.firebasestorage.app',
    iosBundleId: 'com.j3d.j3dSq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCY_hYpzS68qIXdq1I-c8qSCnu1yrOWCk',
    appId: '1:931846761617:ios:8285bb0d8c9bd6527da330',
    messagingSenderId: '931846761617',
    projectId: 'j3d-sq',
    storageBucket: 'j3d-sq.firebasestorage.app',
    iosBundleId: 'com.j3d.j3dSq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB4LkJ8rp_pbGFQ42mozL0KA9ZzXvzHRU',
    appId: '1:931846761617:web:5d1542c326a9981e7da330',
    messagingSenderId: '931846761617',
    projectId: 'j3d-sq',
    authDomain: 'j3d-sq.firebaseapp.com',
    storageBucket: 'j3d-sq.firebasestorage.app',
    measurementId: 'G-FXD1PCWYQ9',
  );
}